<a href="https://colab.research.google.com/github/goutham-kalikrishna/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch

import torch

# Create random tensor

RandomTensor_A = torch.rand(7,7)

RandomTensor_A

tensor([[0.6647, 0.7860, 0.4633, 0.9770, 0.8137, 0.4683, 0.0263],
        [0.4025, 0.7585, 0.9530, 0.0198, 0.7895, 0.3012, 0.9129],
        [0.5364, 0.7659, 0.9352, 0.6359, 0.2880, 0.1230, 0.4761],
        [0.4325, 0.3837, 0.2128, 0.6214, 0.6516, 0.1346, 0.4339],
        [0.1722, 0.7852, 0.0598, 0.7044, 0.1788, 0.8271, 0.9384],
        [0.8076, 0.9503, 0.3448, 0.7433, 0.3350, 0.2728, 0.0766],
        [0.4788, 0.2336, 0.4573, 0.7358, 0.2557, 0.3009, 0.4492]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor

RandomTensor_B = torch.rand(1, 7)

# Perform matrix multiplication

RandomTensor_Matmul_A = torch.matmul(RandomTensor_A, RandomTensor_B.T)
print(RandomTensor_Matmul_A)

RandomTensor_Matmul_B = torch.matmul(RandomTensor_A, RandomTensor_B.reshape(7, 1))
print(RandomTensor_Matmul_B)

RandomTensor_Matmul_C = torch.matmul(RandomTensor_A, RandomTensor_B.view(7, 1))
print(RandomTensor_Matmul_C)

RandomTensor_Matmul_D = torch.matmul(RandomTensor_A, torch.permute(RandomTensor_B, (1, 0)))
print(RandomTensor_Matmul_D)


tensor([[2.8144],
        [2.6560],
        [2.4588],
        [2.0849],
        [2.2113],
        [2.3218],
        [1.8654]])
tensor([[2.8144],
        [2.6560],
        [2.4588],
        [2.0849],
        [2.2113],
        [2.3218],
        [1.8654]])
tensor([[2.8144],
        [2.6560],
        [2.4588],
        [2.0849],
        [2.2113],
        [2.3218],
        [1.8654]])
tensor([[2.8144],
        [2.6560],
        [2.4588],
        [2.0849],
        [2.2113],
        [2.3218],
        [1.8654]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors

RandomTensor_A = torch.rand(7, 7)
RandomTensor_B = torch.rand(1, 7)

# Matrix multiply tensors

RandomTensor_Matmul_A = torch.matmul(RandomTensor_A, RandomTensor_B.T)
RandomTensor_Matmul_A, RandomTensor_Matmul_A.size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [30]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [36]:
import torch

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU

RandomTensor_A = torch.rand(2, 3) # RandomTensor_A = torch.rand(2, 3, device=device)
RandomTensor_B = torch.rand(2, 3)

RandomTensor_A_GPU = RandomTensor_A.to(device)
RandomTensor_B_GPU = RandomTensor_B.to(device)

RandomTensor_A_GPU, RandomTensor_B_GPU

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [37]:
# Perform matmul on tensor_A and tensor_B

RandomTensor_Matmul = torch.matmul(RandomTensor_A_GPU, RandomTensor_B_GPU.T)
RandomTensor_Matmul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [41]:
# Find max
MAX = RandomTensor_Matmul.max() # torch.max(RandomTensor_Matmul)

# Find min
MIN = RandomTensor_Matmul.min()

MAX, MIN

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [42]:
# Find arg max
MAX_ARG = RandomTensor_Matmul.argmax() # torch.argmax(RandomTensor_Matmul)

# Find arg min
MIN_ARG = RandomTensor_Matmul.argmin()

MAX_ARG, MIN_ARG

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [46]:
# Set seed

torch.manual_seed(7)

# Create random tensor

RandomTensor_A = torch.rand(1, 1, 1, 10)

# Remove single dimensions
RES = RandomTensor_A.squeeze()

# Print out tensors and their shapes
print(RandomTensor_A, RandomTensor_A.shape)
print(RES, RES.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
